/**
 * Production-Grade Email Sanitization and Validation
 * Filters out false-positive emails generated by website builders, tracking pixels,
 * image filenames, CDN assets, and placeholder templates.
 */

export const EMAIL_REGEX = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g;

export const IGNORED_DOMAINS = new Set([
  "sentry.io",
  "wixpress.com",
  "schema.org",
  "domain.com",
  "example.com",
  "square.site",
  "shopify.com",
  "wordpress.org",
  "wix.com",
  "squarespace.com",
  "godaddy.com",
  "cloudflare.com",
  "google.com",
  "gstatic.com",
  "facebook.com",
  "instagram.com",
  "twitter.com",
  "gravatar.com",
  "mysite.com",
  "mystore.com",
  "my-store.com",
  "templatemonster.com",
  "envato.com"
]);

export const JUNK_EXTENSIONS = new Set([
  "png", "jpg", "jpeg", "svg", "webp", "gif", "ico", "css", "js", "woff", "woff2", "ttf"
]);

export const JUNK_LOCAL_PATTERNS = [
  /^noreply$/i,
  /^no-reply$/i,
  /^mailer-daemon$/i,
  /^support@wix/i,
  /^press@google/i,
  /icon/i,
  /logo/i,
  /avatar/i,
  /filename/i,
  /assets/i,
  /placeholder/i
];

/**
 * Validates and normalizes an array of raw matched emails.
 * @param {string[]} rawEmails
 * @returns {string[]} Array of verified, unique lowercase emails.
 */
export function cleanEmails(rawEmails) {
  if (!Array.isArray(rawEmails) || rawEmails.length === 0) return [];

  const verified = new Set();

  for (let email of rawEmails) {
    if (typeof email !== "string") continue;
    email = email.toLowerCase().trim();

    // Remove trailing dot if regex grabbed sentence end
    if (email.endsWith(".")) email = email.slice(0, -1);

    const parts = email.split("@");
    if (parts.length !== 2) continue;
    const [local, domain] = parts;

    // RFC 5321 length limits
    if (!local || local.length > 64 || !domain || domain.length > 255) continue;

    // Check domain extensions against image file types
    const domainParts = domain.split(".");
    const tld = domainParts[domainParts.length - 1];
    if (JUNK_EXTENSIONS.has(tld)) continue;

    // Filter out blacklisted platform/CMS/CDN domains
    if (IGNORED_DOMAINS.has(domain)) continue;
    let isIgnoredDomain = false;
    for (const d of IGNORED_DOMAINS) {
      if (domain.endsWith(`.${d}`)) {
        isIgnoredDomain = true;
        break;
      }
    }
    if (isIgnoredDomain) continue;

    // Filter local part patterns
    if (JUNK_LOCAL_PATTERNS.some((pattern) => pattern.test(local))) continue;

    verified.add(email);
  }

  return Array.from(verified);
}
